<#
.SYNOPSIS
    Builds WitsmlExplorer (StoreExplorer) and packages it into an installer zip.

.DESCRIPTION
    This script:
      1. Builds the React/Vite frontend for the /storeExplorer sub-path.
      2. Publishes the ASP.NET Core 8 API.
      3. Copies the IIS configuration files.
      4. Creates StoreExplorer-Installer.zip ready to deploy on the target IIS server.

.PARAMETER OutputDir
    Directory where the installer zip will be written. Defaults to .\dist.

.PARAMETER SkipFrontend
    Skip the frontend build (useful if it was already built).

.PARAMETER SkipApi
    Skip the API publish step.

.EXAMPLE
    .\Build-Installer.ps1
    .\Build-Installer.ps1 -OutputDir C:\Builds
#>

[CmdletBinding()]
param(
    [string]$OutputDir   = "$PSScriptRoot\dist",
    [switch]$SkipFrontend,
    [switch]$SkipApi
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------
function Write-Step([string]$msg) {
    Write-Host "`n==> $msg" -ForegroundColor Cyan
}

function Assert-Command([string]$cmd, [string]$hint) {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
        Write-Error "Required command '$cmd' not found. $hint"
    }
}

# ---------------------------------------------------------------------------
# Locate repo root (one level up from Installer/)
# ---------------------------------------------------------------------------
$repoRoot = (Resolve-Path "$PSScriptRoot\..").Path
$frontendDir = Join-Path $repoRoot "Src\WitsmlExplorer.Frontend"
$apiDir      = Join-Path $repoRoot "Src\WitsmlExplorer.Api"

Write-Step "Repository root: $repoRoot"

# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------
Write-Step "Checking prerequisites"
Assert-Command "dotnet" "Install .NET 8 SDK from https://dotnet.microsoft.com/download"
Assert-Command "node"   "Install Node.js 20+ from https://nodejs.org/"
Assert-Command "yarn"   "Run: npm install -g yarn"

$dotnetVersion = (dotnet --version)
Write-Host "  dotnet : $dotnetVersion"
Write-Host "  node   : $(node --version)"
Write-Host "  yarn   : $(yarn --version)"

# ---------------------------------------------------------------------------
# Build frontend
# ---------------------------------------------------------------------------
if (-not $SkipFrontend) {
    Write-Step "Building frontend (Vite, base=/storeExplorer/)"
    Push-Location $frontendDir
    try {
        yarn install --frozen-lockfile
        yarn build          # Uses .env.production → base=/storeExplorer/
    }
    finally { Pop-Location }
}

$frontendDist = Join-Path $frontendDir "dist"
if (-not (Test-Path $frontendDist)) {
    Write-Error "Frontend dist not found at '$frontendDist'. Run without -SkipFrontend."
}

# ---------------------------------------------------------------------------
# Publish API
# ---------------------------------------------------------------------------
$apiPublishDir = Join-Path $PSScriptRoot "tmp_publish\api"

if (-not $SkipApi) {
    Write-Step "Publishing ASP.NET Core API"
    if (Test-Path $apiPublishDir) { Remove-Item $apiPublishDir -Recurse -Force }

    dotnet publish "$apiDir\WitsmlExplorer.Api.csproj" `
        --configuration Release `
        --output $apiPublishDir `
        --runtime win-x64 `
        --self-contained false `
        /p:UseAppHost=true
}

if (-not (Test-Path $apiPublishDir)) {
    Write-Error "API publish output not found at '$apiPublishDir'. Run without -SkipApi."
}

# ---------------------------------------------------------------------------
# Stage the installer package
# ---------------------------------------------------------------------------
Write-Step "Staging installer package"

$stageDir = Join-Path $PSScriptRoot "tmp_stage"
if (Test-Path $stageDir) { Remove-Item $stageDir -Recurse -Force }
New-Item -ItemType Directory -Path $stageDir | Out-Null

# --- frontend ---
$stageFrontend = Join-Path $stageDir "frontend"
Copy-Item $frontendDist $stageFrontend -Recurse

# Overwrite the web.config generated by Vite with our IIS SPA config
Copy-Item "$PSScriptRoot\frontend-web.config" "$stageFrontend\web.config" -Force

# --- api ---
$stageApi = Join-Path $stageDir "api"
Copy-Item $apiPublishDir $stageApi -Recurse

# Overwrite appsettings with the IIS-specific production settings
Copy-Item "$PSScriptRoot\appsettings.iis.json" "$stageApi\appsettings.json" -Force

# --- install script ---
Copy-Item "$PSScriptRoot\Install-StoreExplorer.ps1" $stageDir

# ---------------------------------------------------------------------------
# Create zip
# ---------------------------------------------------------------------------
Write-Step "Creating installer zip"

if (-not (Test-Path $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir | Out-Null }

$zipPath = Join-Path $OutputDir "StoreExplorer-Installer.zip"
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }

Compress-Archive -Path "$stageDir\*" -DestinationPath $zipPath

Write-Host "`n  Installer zip: $zipPath" -ForegroundColor Green

# ---------------------------------------------------------------------------
# Cleanup temp directories
# ---------------------------------------------------------------------------
Remove-Item (Join-Path $PSScriptRoot "tmp_publish") -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item $stageDir -Recurse -Force -ErrorAction SilentlyContinue

Write-Step "Done"
Write-Host @"

Next steps
----------
1. Copy StoreExplorer-Installer.zip to the target Windows/IIS machine.
2. Unzip it to a temporary location (e.g. C:\Temp\StoreExplorer-Installer).
3. Open PowerShell as Administrator and run:
       Set-ExecutionPolicy RemoteSigned -Scope Process
       .\Install-StoreExplorer.ps1
"@ -ForegroundColor Yellow
